Repository ubccr/xdmod-supremm, pull requests merged in 2018-03, with the labels that each got.

#79 Update RPM spec file
  xdmod-supremm.spec.in
Labels: enhancement

#87 Update compatibility table
  docs/supremm-upgrade-overview.md
Labels: documentation

#86 Update documentation and changelog
  CHANGELOG.md
  docs/supremm-processing-configuration.md
  docs/supremm-upgrade.md
Labels: documentation

#88 Release preparations
  configuration/portal_settings.d/supremm.ini
  xdmod-supremm.spec.in
Labels: release prep

#91 update shippable docker image
  shippable.yml
  xdmod-supremm.spec.in
Labels: release prep

#96 Release preparations
  CHANGELOG.md
  build.json
  configuration/portal_settings.d/supremm.ini
  docs/supremm-upgrade.md
  xdmod-supremm.spec.in
Labels: release prep

#97 Version sync
  CHANGELOG.md
  classes/OpenXdmod/Setup/SupremmDbSetup.php
  docs/supremm-upgrade.md
  tests/integration_tests/scripts/xdmod-setup.tcl
  xdmod-supremm.spec.in
Labels: version sync
