Repository ubccr/xdmod-supremm, pull requests merged in 2022-01, with the labels that each got.

#289 Setup Efficiency Controller Provider for adding new REST endpoints related to efficiency tab.
  build.json
  classes/Rest/Controllers/EfficiencyControllerProvider.php
  configuration/efficiency_analytics.json
  configuration/rest.d/efficiency.json
  xdmod-supremm.spec.in
Labels: feature request

#285 Handle case where ingest/aggregation takes a long time and DB conn timeout.
  classes/DB/EtlJournalHelper.php
Labels: bug

#293 Add the end_time of the job to the lookup for tg_job_id
  etl/js/config/supremm/etl.schema.js
Labels: bug

#302 Update version of nodejs to the current LTS.
  .circleci/config.yml
  tests/ci/scripts/install_dependencies.sh
  xdmod-supremm.spec.in
Labels: dependency update

#303 Fix list of realms to test.
  .circleci/config.yml
Labels: bug

#301 Change sizing of scatter and drill down charts in efficiency tab.
  html/gui/js/modules/efficiency/AnalyticPanel.js
  html/gui/js/modules/efficiency/ScatterPlotPanel.js
Labels: bug
