Repository ubccr/xdmod-supremm, pull requests merged in 2022-06, with the labels that each got.

#329 Fix test and typo
  tests/integration_tests/scripts/validate.sh
Labels: bug

#331 Remove old migrations
  configuration/etl/etl_sql.d/supremm/migration-9_5_0-10_0_0.sql
  db/migrations/8.0.0-8.1.0/modw_supremm.sql
Labels: code cleanup

#321 Centos8 changes
  .circleci/config.yml
  classes/DataWarehouse/Query/SUPREMM/JobMetadata.php
  classes/DataWarehouse/Query/SUPREMM/SupremmDbInterface.php
  composer.json
  composer.lock
  tests/ci/Docker/Dockerfile.centos8
  tests/ci/Docker/Dockerfile.centos8.base
  tests/ci/Docker/Dockerfile.rockylinux8
  tests/ci/Docker/Dockerfile.rockylinux8.base
  tests/integration_tests/lib/REST/Warehouse/JobViewerTest.php
  xdmod-supremm.spec.in
Labels: qa
