Repository ubccr/xdmod-supremm, pull requests merged in 2023-12, with the labels that each got.

#367 Fix CircleCI test result paths.
  .circleci/config.yml
Labels: bug

#354 Add raw data regression tests.
  .circleci/config.yml
  tests/artifacts/regression/current/expected/reference/raw-data/supremm-fields-and-filters.json
  tests/artifacts/regression/current/expected/reference/raw-data/supremm.json
  tests/regression/lib/Rest/WarehouseRawDataSupremmTest.php
  tests/regression/runtests.sh
Labels: qa

#343 Catch PHP command-line errors in CircleCI.
  .circleci/config.yml
Labels: qa

#369 Fix raw data regression test.
  tests/regression/lib/Rest/WarehouseRawDataSupremmTest.php
Labels: bug, qa

#256 Refactor job data set analysis fields
  classes/DataWarehouse/Query/SUPREMM/JobDataset.php
  docs/customization.md
  etl/js/config/supremm/etl.schema.js
Labels: enhancement, ETL
