Repository ubccr/xdmod-supremm, pull requests merged in 2024-06, with the labels that each got.

#381 Update raw data regression tests to expect JSON text sequences.
  tests/artifacts/regression/current/expected/reference/raw-data/supremm-fields-and-filters.json
  tests/artifacts/regression/current/expected/reference/raw-data/supremm.json
Labels: qa

#373 Updates to Support PHP7.4
  .circleci/config.yml
  background_scripts/supremm_sharedjobs.php
  background_scripts/xdmod-supremm-admin
  classes/Rest/Controllers/SupremmDataflowControllerProvider.php
  composer.json
  composer.lock
  tests/artifacts/regression/chartFilterTests.json
  tests/component/lib/DataWarehouse/Query/SUPREMM/SupremmDbInterfaceTest.php
  tests/component/phpunit.xml.dist
  tests/integration/lib/Controllers/MetricExplorerControllerTest.php
  tests/integration/lib/Controllers/UserInterfaceControllerTest.php
  tests/integration/lib/REST/EfficiencyControllerProviderTest.php
  tests/integration/lib/REST/SupremmDataflowControllerProviderTest.php
  tests/integration/lib/REST/Warehouse/DataTest.php
  tests/integration/lib/REST/Warehouse/JobViewerTest.php
  tests/integration/lib/REST/internal_dashboard/DashboardSupremmTest.php
  tests/integration/phpunit.xml.dist
  tests/regression/lib/Controllers/UsageExplorerSupremmTest.php
  tests/regression/lib/Rest/WarehouseRawDataSupremmTest.php
  tests/regression/phpunit.xml.dist
  tests/unit/lib/DataWarehouse/Query/SUPREMM/JobMetadataTest.php
  tests/unit/lib/DataWarehouse/Query/SUPREMM/JobTimeseriesTest.php
  tests/unit/phpunit.xml.dist
Labels: compatibility update

#382 Add citation for the XDMoD paper.
  README.md
Labels: documentation
