Repository ubccr/xdmod-supremm, pull requests merged in 2024-05, with the labels that each got.

#360 Update the efficiency tab for plotly
  .gitignore
  classes/Rest/Controllers/EfficiencyControllerProvider.php
  configuration/efficiency_analytics.json
  docs/analytics.md
  etl/js/config/supremm/etl.schema.js
  html/.eslintrc.json
  html/gui/css/Efficiency.css
  html/gui/images/left_arrow.png
  html/gui/images/up_arrow.png
  html/gui/js/modules/dashboard/UserJobEfficiencyComponent.js
  html/gui/js/modules/efficiency/AnalyticPanel.js
  html/gui/js/modules/efficiency/Efficiency.js
  html/gui/js/modules/efficiency/FilterPanel.js
  html/gui/js/modules/efficiency/ScatterPlotPanel.js
  tests/integration/lib/Controllers/UserInterfaceControllerTest.php
  tests/integration/lib/REST/EfficiencyControllerProviderTest.php
Labels: EfficiencyTab

#377 Replace jQuery with native JS
  html/.eslintrc.json
  html/gui/js/modules/efficiency/Efficiency.js
  html/gui/js/modules/efficiency/FilterPanel.js
  html/internal_dashboard/supremm/css/style.css
  html/internal_dashboard/supremm/js/stats.js
  html/internal_dashboard/supremm/stats.php
Labels: dependency update

#353 Sanitize NAN values from timeseries data
  classes/DataWarehouse/Query/SUPREMM/JobMetadata.php
Labels: bug
